spring.application.name=smart-devcollab
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/smart_devcollab?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=SmartDevCollabSecretKeyForAcademicProjectMustBeLongEnough123456
app.jwt.expiration=86400000

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-swallow-size=20MB

gemini.api.key=AQ.Ab8RN6JJfnNsxxJLqaJU9ZvHmovr97x8xnrbj9Ja_BxeZ0qxxQ
gemini.model=gemini-2.5-flash